version: '3'
services:
  redis:
    container_name: redis
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
  php-fpm:
    container_name: php-fpm
    build: ./php-fpm
    ports:
      - "9000:9000"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./www:/var/www
      - ./php-fpm/logs:/usr/local/var/log
    depends_on:
      - redis
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
    - "8001:80"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./www:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm



